name: qrsend
description: "Send Files via Streaming QR Codes"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.10.9

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  crypto: ^3.0.7
  file_picker: ^10.3.10
  desktop_drop: ^0.7.0
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  camera: ^0.12.0
  camera_windows: ^0.2.6+4
  zxing2: ^0.2.4
  image: ^4.8.0
  cross_file: ^0.3.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
